"""initial schema

Revision ID: 0b65a9ee802e
Revises: 
Create Date: 2026-08-16 19:52:12.129850
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0b65a9ee802e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('district', sa.String(length=64), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('footprint', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('floor_area_m2', sa.Float(), nullable=False),
    sa.Column('roof_area_m2', sa.Float(), nullable=False),
    sa.Column('glazing_area_m2', sa.Float(), nullable=False),
    sa.Column('roof_orientation', sa.String(length=8), nullable=False),
    sa.Column('hvac_type', sa.String(length=32), nullable=False),
    sa.Column('hvac_age_yr', sa.Integer(), nullable=False),
    sa.Column('insulation_quality', sa.String(length=16), nullable=False),
    sa.Column('occupancy_pattern', sa.String(length=32), nullable=False),
    sa.Column('annual_kwh', sa.Float(), nullable=False),
    sa.Column('annual_kwh_source', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_building_district'), 'building', ['district'], unique=False)
    op.create_table('integrity_checkpoint',
    sa.Column('building_id', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seq', sa.BigInteger(), nullable=False),
    sa.Column('head_sig', sa.LargeBinary(length=32), nullable=False),
    sa.PrimaryKeyConstraint('building_id', 'ts')
    )
    op.create_table('intervention',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('end_use', sa.String(length=16), nullable=False),
    sa.Column('exclusive_group', sa.String(length=32), nullable=False),
    sa.Column('adj_key', sa.String(length=32), nullable=False),
    sa.Column('cost_type', sa.String(length=24), nullable=False),
    sa.Column('cost_value', sa.Float(), nullable=False),
    sa.Column('saving_frac', sa.Float(), nullable=False),
    sa.Column('service_life_yr', sa.Integer(), nullable=False),
    sa.Column('embodied_type', sa.String(length=24), nullable=False),
    sa.Column('embodied_value', sa.Float(), nullable=False),
    sa.Column('applies_if', sa.Text(), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=False),
    sa.Column('loaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimization_run',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('budget_egp', sa.Float(), nullable=False),
    sa.Column('objective', sa.String(length=32), nullable=False),
    sa.Column('solver', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('max_funded_per_district', sa.Integer(), nullable=True),
    sa.Column('objective_value', sa.Float(), nullable=False),
    sa.Column('total_cost_egp', sa.Float(), nullable=False),
    sa.Column('total_kwh_saving', sa.Float(), nullable=False),
    sa.Column('total_benefit_kgco2e', sa.Float(), nullable=False),
    sa.Column('buildings_funded', sa.Integer(), nullable=False),
    sa.Column('solve_ms', sa.Float(), nullable=False),
    sa.Column('inputs_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_run_created_at'), 'optimization_run', ['created_at'], unique=False)
    op.create_table('allocation',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('building_id', sa.String(length=32), nullable=False),
    sa.Column('building_code', sa.String(length=64), nullable=False),
    sa.Column('district', sa.String(length=64), nullable=False),
    sa.Column('candidate_key', sa.String(length=255), nullable=False),
    sa.Column('intervention_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('cost_egp', sa.Float(), nullable=False),
    sa.Column('annual_kwh_saving', sa.Float(), nullable=False),
    sa.Column('lifetime_benefit_kgco2e', sa.Float(), nullable=False),
    sa.Column('annual_egp_saving', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['optimization_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocation_building_id'), 'allocation', ['building_id'], unique=False)
    op.create_index(op.f('ix_allocation_run_id'), 'allocation', ['run_id'], unique=False)
    op.create_table('anomaly',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('building_id', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_kw', sa.Float(), nullable=False),
    sa.Column('expected_kw', sa.Float(), nullable=False),
    sa.Column('residual', sa.Float(), nullable=False),
    sa.Column('robust_z', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'ts', name='uq_anomaly_building_ts')
    )
    op.create_index(op.f('ix_anomaly_building_id'), 'anomaly', ['building_id'], unique=False)
    op.create_index(op.f('ix_anomaly_ts'), 'anomaly', ['ts'], unique=False)
    op.create_table('candidate',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('building_id', sa.String(length=32), nullable=False),
    sa.Column('district', sa.String(length=64), nullable=False),
    sa.Column('intervention_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('cost_egp', sa.Float(), nullable=False),
    sa.Column('annual_kwh_saving', sa.Float(), nullable=False),
    sa.Column('lifetime_benefit_kgco2e', sa.Float(), nullable=False),
    sa.Column('annual_egp_saving', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('inputs_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_candidate_building_id'), 'candidate', ['building_id'], unique=False)
    op.create_index(op.f('ix_candidate_district'), 'candidate', ['district'], unique=False)
    op.create_index(op.f('ix_candidate_inputs_hash'), 'candidate', ['inputs_hash'], unique=False)
    op.create_table('forecast',
    sa.Column('building_id', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('yhat', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('made_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('building_id', 'ts')
    )
    op.create_table('reading',
    sa.Column('building_id', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kw', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('sig', sa.LargeBinary(length=32), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('building_id', 'ts')
    )
    op.create_index('ix_reading_building_seq', 'reading', ['building_id', 'seq'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reading_building_seq', table_name='reading')
    op.drop_table('reading')
    op.drop_table('forecast')
    op.drop_index(op.f('ix_candidate_inputs_hash'), table_name='candidate')
    op.drop_index(op.f('ix_candidate_district'), table_name='candidate')
    op.drop_index(op.f('ix_candidate_building_id'), table_name='candidate')
    op.drop_table('candidate')
    op.drop_index(op.f('ix_anomaly_ts'), table_name='anomaly')
    op.drop_index(op.f('ix_anomaly_building_id'), table_name='anomaly')
    op.drop_table('anomaly')
    op.drop_index(op.f('ix_allocation_run_id'), table_name='allocation')
    op.drop_index(op.f('ix_allocation_building_id'), table_name='allocation')
    op.drop_table('allocation')
    op.drop_index(op.f('ix_optimization_run_created_at'), table_name='optimization_run')
    op.drop_table('optimization_run')
    op.drop_table('intervention')
    op.drop_table('integrity_checkpoint')
    op.drop_index(op.f('ix_building_district'), table_name='building')
    op.drop_table('building')
    # ### end Alembic commands ###
