"""Generate a .env with fresh secrets. Run once, before the first `docker compose up`.

Secrets are generated locally and never leave the machine. .env is gitignored and
must stay that way - the integrity guarantee in F5 rests on the signing key not
living in the repository or in the database volume.

    python scripts/setup_env.py            # refuses to overwrite an existing .env
    python scripts/setup_env.py --force    # regenerate (invalidates every signature)
"""

from __future__ import annotations

import argparse
import secrets
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ENV_PATH = ROOT / ".env"

TEMPLATE = """\
# Generated by scripts/setup_env.py. Do not commit.

# Integrity signing key (F5). Changing this invalidates every existing signature,
# which is why regeneration requires --force.
GEMP_HMAC_KEY={hmac_key}

GEMP_DB_HOST=timescaledb
GEMP_DB_PORT=5432
GEMP_DB_NAME=gemp
GEMP_DB_USER=gemp
GEMP_DB_PASSWORD={db_password}

GEMP_DB_RO_USER=gemp_ro
GEMP_DB_RO_PASSWORD={db_ro_password}

GEMP_MQTT_HOST=mosquitto
GEMP_MQTT_PORT=1883
GEMP_MQTT_USER=gemp
GEMP_MQTT_PASSWORD={mqtt_password}

GEMP_GRAFANA_PASSWORD={grafana_password}

# 1 wall-second = this many data-seconds. 720 => 12 data-minutes per second, so a
# six-month backfill replays in about five hours, and a demonstration shows a full
# day of load in two minutes. All rolling windows are evaluated in DATA time.
GEMP_SIM_SPEED=720
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    if ENV_PATH.exists() and not args.force:
        print(f"{ENV_PATH} already exists. Use --force to regenerate.")
        print("Regenerating the signing key invalidates every stored signature.")
        return 1

    ENV_PATH.write_text(
        TEMPLATE.format(
            hmac_key=secrets.token_hex(32),
            db_password=secrets.token_urlsafe(24),
            db_ro_password=secrets.token_urlsafe(24),
            mqtt_password=secrets.token_urlsafe(18),
            grafana_password=secrets.token_urlsafe(12),
        ),
        encoding="utf-8",
    )
    print(f"wrote {ENV_PATH}")
    print("next: python scripts/setup_mqtt_auth.py   (needs Docker running)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
